name: likenoother
favicon: null
layout_spectrum: 0.8844
typography_spectrum: 0.6000741051975638
title: Like No Other - Consultancy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#ffffff'
    - '#4a4a4a'
    - '#797979'
    - '#d8d8d8'
  brandStrength: 0.75
  lightness: 0.005436247913166881
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
