name: likenoother
favicon: null
layout_spectrum: 0.09923
typography_spectrum: 0.69641
title: Like No Other - Consultancy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#ffffff'
    - '#4a4a4a'
    - '#797979'
    - '#d8d8d8'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
